const STATUS_IDLE = 'IDLE';
const STATUS_BUSY = 'BUSY';
const STATUS_FAILED = 'FAILED';
const STATUS_COMPLETED = 'COMPLETED';

module.exports = { STATUS_IDLE, STATUS_BUSY, STATUS_FAILED, STATUS_COMPLETED };
